test: update 'scripts/run_tests' to generate coverage/lcov.info

diff --git a/scripts/run_tests b/scripts/run_tests
--- a/scripts/run_tests
+++ b/scripts/run_tests
@@ -23,6 +23,21 @@ if [[ -n $FILES ]] ; then
     pdm run mypy $FILES
 fi
 
+# Generate a coverage report in lcov format even if pytest fails due to
+# lacking coverage. The report can then be used by an IDE to indicate
+# coverage directly in your editor window. Special care must be taken
+# when working on code that isn't covered by unit tests.
+#
+# recommended extension for VS Code:
+# https://marketplace.visualstudio.com/items?itemName=markis.code-coverage
+generate_lcov() {
+    mkdir -p coverage
+    pdm run coverage-lcov --output_file_path=coverage/lcov.info
+}
+trap generate_lcov EXIT
+
+pdm run pytest --cov=feeph.i2c --cov-report= tests/
+
 echo "----------------------------------------------------------------------"
 echo "If you reached this far you passed. Congratulations!"
 echo "----------------------------------------------------------------------"
